# Generated by Django 2.1.7 on 2019-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
