# Generated by Django 2.1.7 on 2019-03-31 20:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='test1'),
            preserve_default=False,
        ),
    ]
